// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCx6bVQo0YVYDLsj7OiOB98QZI9soUUR4',
    appId: '1:1025614666815:web:a51b9aeeeeff9cfbb2ac8a',
    messagingSenderId: '1025614666815',
    projectId: 'greenguard-46f96',
    authDomain: 'greenguard-46f96.firebaseapp.com',
    storageBucket: 'greenguard-46f96.firebasestorage.app',
    measurementId: 'G-Q6M291C4D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMuYEvlxlcZlIau04D3nE5zA91TcIvI8',
    appId: '1:1025614666815:android:f1068825805d2314b2ac8a',
    messagingSenderId: '1025614666815',
    projectId: 'greenguard-46f96',
    storageBucket: 'greenguard-46f96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIaX-OYITBPD-QwXRQQr98mcC_ZEGTh7c',
    appId: '1:1025614666815:ios:398e19427685fdbfb2ac8a',
    messagingSenderId: '1025614666815',
    projectId: 'greenguard-46f96',
    storageBucket: 'greenguard-46f96.firebasestorage.app',
    iosClientId: '1025614666815-b9f7oketgk935okcn4itmf44i8sbap65.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIaX-OYITBPD-QwXRQQr98mcC_ZEGTh7c',
    appId: '1:1025614666815:ios:398e19427685fdbfb2ac8a',
    messagingSenderId: '1025614666815',
    projectId: 'greenguard-46f96',
    storageBucket: 'greenguard-46f96.firebasestorage.app',
    iosClientId: '1025614666815-b9f7oketgk935okcn4itmf44i8sbap65.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCx6bVQo0YVYDLsj7OiOB98QZI9soUUR4',
    appId: '1:1025614666815:web:ee8a4f6becc7ec88b2ac8a',
    messagingSenderId: '1025614666815',
    projectId: 'greenguard-46f96',
    authDomain: 'greenguard-46f96.firebaseapp.com',
    storageBucket: 'greenguard-46f96.firebasestorage.app',
    measurementId: 'G-3Q9ML98QVN',
  );
}
